.github/workflows/R-CMD-check.yaml
DESCRIPTION

Upstream dependencies support R >= 3.4 (e.g. r2dii.match). This is
reasonable as we are now on R 4.0 and we check on R release, oldrel
(3.6), 3.5, and 3.4.

Depend on R >= 3.4

---

README.Rmd
README.md

By example, encourage users to name explicitely every argument
after the first one or two.

Style README

---

R/target_market_share_company.R
R/target_market_share_portfolio.R
tests/testthat/test-target_market_share_company.R
tests/testthat/test-target_market_share_portfolio.R

* Added a test to identify bug where portfolio and targets did not originate from same value at start year
* Fixed bug
See reprex below: 
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(ggplot2)
library(r2dii.data)
library(r2dii.match)
library(r2dii.analysis)
matched <- match_name(loanbook_demo, ald_demo) %>%
prioritize()
loanbook_joined_to_ald_scenario <- matched %>% 
join_ald_scenario(
ald = ald_demo, 
scenario = scenario_demo_2020, 
region_isos = region_isos_demo
)
market_share_targets_portfolio <- loanbook_joined_to_ald_scenario %>% 
summarize_portfolio_production() %>% …
```

87 bugfix regional scenario targets

---

tests/testthat/test-target_market_share.R

Very small/ harmless PR.
Extended a test to ensure that sector and region are properly grouped, and output sensible targets. Sorta kills two birds with one stone. 
Closes #47

Add multiple sector tests

---

R/target_sda.R
man/target_sda.Rd
tests/testthat/test-target_sda.R

I noticed that the example target_sda output had `NA`s. 
This was a result of input data have `NA`s in the `emission_factor` columns for some sectors. 
`target_sda` now aborts if any crucial columns contain `NA`s. 
Closes #156

`target_sda()` with missing crucial values errors with informative message

---

R/target_sda.R
R/utils.R
tests/testthat/test-target_sda.R

This relates to a bug identified by multiple users, where `projected` `emission_factors` were unreasonably large. 
This was a result of the input data having duplicate `id_loans` per loan. The result was that, while the loan weights was calculated per `id_loan`, the `emission_factor` was summed across each loan weight, causing double-counting (sometimes more). 
I decided to go the more harsh route, and cause the function to `error` if input `id_loans` were duplicated. This will save us headache down the road, as these `id`s should uniquely identify EVERY loan (otherwise we're gonna have problems). 
I also noticed that the `emission_factor` was still being weighted when `by_company = TRUE` which doesn't make sense, so fixed that as well. 
Maybe closes #160

Check that `id_loan` is not duplicated

---

R/target_market_share.R
README.md
man/target_market_share.Rd
vignettes/r2dii-analysis.Rmd

In prepping `r2dii.analysis` for CRAN, I noticed that the Get Started page (and a few other things) referred to the "old" `target_market_share()` output columns. I have updated everything accordingly. 
Closes #195

update get started

---

NEWS.md
vignettes/r2dii-analysis.Rmd

The hyperlinks to Market Share Approach and SDA on the "Get Started" tab of the website now point to the correct places. 
Thanks @apmanning
Closes #222

Fix Get Started website links

---

NEWS.md
R/summarize_weighted_production.R
tests/testthat/test-target_market_share.R

`summarize_unweighted_production` now drops the crucial column `id_loan` and selects distinct values, to avoid erroneous double-counting when calculating the `unweighted` company production. 
Closes #239

Fix unweighted company

---

NEWS.md
R/target_market_share.R
tests/testthat/test-target_market_share.R

Closes #218
This is not the most elegant solution, as I am simply re-weighting the `technology_share`, after it is calculated and summarized, which sorta feels like cheating, but I can't think of something more clever. 
The issue is that, for example, if we have company level results, we may have a table like: 
``` r
tibble::tribble(
~name_company, ~technology, ~technology_share,
"a",  "electric",               0.5,
"a",       "ice",               0.5,
"b",  "electric",              0.25,
"b",       "ice",              0.75
)
#> # A tibble: 4 x 3
#>   name_company technology technology_share
#>   <chr>        <chr>                 <dbl>
#> 1 a            electric               0.5 
#> 2 a            ice                    0.5 
#> 3 b            electric               0.25
#> 4 b …
```

Reweight `technology_share` prior to output. 

---

NEWS.md
R/summarize_weighted_production.R
tests/testthat/test-target_market_share.R

Unweighted market share target outputs correctly with multiple input `level`s

---

DESCRIPTION
R/summarize_weighted_production.R
tests/testthat/test-target_market_share.R

Closes #253
Unweighted production by company should ignore loan_size_* columns.

253 multi laon by company yields unweighted prod as ald

---

NEWS.md
R/target_market_share.R
tests/testthat/test-target_market_share.R

As the first step of `target_market_share`, I now aggregate by `id_loan` to the same company on the input data. We likely could have done this much earlier, I don't recall now why I didn't... but all tests are passing and everything looks good so I think it should be ok!
Closes #262

Aggregate all loans to the same company in `target_market_share`

---

DESCRIPTION
NEWS.md
R/target_market_share.R
tests/testthat/test-target_market_share.R

Closes #267
Thanks for flagging the issue @georgeharris2deg 
I elected to go the more restrictive route since there is some internal aggregations and groupings happening, it's impossible to know arbitrarily how to handle any unexpected column. 
This option will prevent the user from even being able to input unexpected columns, even if they want to. Happy to revisit the decision, but I think it's safest for now.

`target_market_share` errors if input `data` has unexpected columns

---

R/summarize_weighted_production.R
R/target_market_share.R

This PR is strictly refactoring, and should not change the expected functionality of the code whatsoever. Most of the refactoring occurs in `target_market_share`, although I briefly touched `summarize_weighted_production` as I noticed something weird about the interface of the functions. 
The main change can be thought of as follows. Previously, the function `target_market_share()` worked something like this: 
- Join input datasets together
- Add a metric AND summarize (either to company level, or to portfolio level)
- Add targets 
- Tidy-up a bit and output
Now, the function works more like this: 
- Join input datasets together
- Add a metric AND summarize (strictly to company level)
- Add targets 
- Maybe aggregate to portfolio level
- Tidy-up a bit and output
This will make it easier …

Refactor `target_market_share` (#277)

---

NEWS.md
R/summarize_weighted_production.R
R/target_market_share.R
tests/testthat/test-target_market_share.R

The `level` column is only really used in the matching process for calculating coverage statistics. 
In the actual analysis, we should ignore this column. 
Maybe closes #265

Dont group_by `level` in `target_market_share()`

---

NEWS.md
R/summarize_weighted_production.R
R/target_market_share.R
README.md
tests/testthat/test-target_market_share.R

The `target_*` values of `technology_share` should be calculated as follows (in line with the methodology): 
1 - Calculate the `production_target` for each company (without weighting) 
2 - Calculate the `technology_share_target` for each company (without weighting)
3 - Apply the portfolio_weight to each of `production`, `technology_share`, `production_target` and `technology_share_target`
This has been achieved. 
@maurolepore this is an MVP solution, as this has been an open bug for some time. Please review (and note that I recognize that some of my solutions are not so elegant). 
Also @georgeharris2deg if you could please have a look at this it would be much appreciated. 
I would rather we get the solution out the door, and we can refactor later. 
Closes #277

`technology_share` for `target_*` is now properly calculated and weighted

---

NEWS.md

My mistake. I forgot to remove a reference to a
version that never made it to CRAN.﻿

Remove reference to non-existing release

---

NEWS.md
R/target_market_share.R
tests/testthat/test-target_market_share.R

Any `smsp` targets that are calculated negatively, will be attenuated to 0. 
This is a **technical** solution but does not solve the larger **methodological** issue, which is to be discussed by the analyst team in the next PACTA bi-weekly. 
Prior to merging this, I would like approval from @georgeharris2deg that he has read and understood this technical interim solution. 
Closes #336

`target_market_share` no longer allows for negative `production` targets

---

NEWS.md
R/summarize_weighted_production.R
R/target_market_share.R
tests/testthat/test-target_market_share.R

This PR is a sparse implementation of @Antoine-Lalechere's fix to set `technology_share` values to `0` should they have no initial sectoral production (#348). 
Closes #306 
Closes [ADO 876](https://dev.azure.com/2DegreesInvesting/2DegreesInvesting/_workitems/edit/876)

Set `technology_share` to 0 for companies with zero initial sectoral production

---

DESCRIPTION
data-raw/sysdata.R

This PR merges not into master but into 354_*, which is
a way to say it depends on #354.
Closes #353
When I tried to source data-raw/sysdata.R I got an error,
showing that sysdata was no longer reproducible. This pr
makes sysdata reproducible again, by ensuring two columns
we want to join by of the same type.

MERGE 2nd: Make sysdata reproducible

---

R/join_ald_scenario.R
R/summarize_weighted_production.R
R/target_market_share.R
R/target_sda.R
man/join_ald_scenario.Rd
man/summarize_weighted_production.Rd
man/target_market_share.Rd
man/target_sda.Rd
tests/testthat/test-join_ald_scenario.R
tests/testthat/test-summarize_weighted_production.R
tests/testthat/test-target_sda.R

Closes #356
Background: CRAN archived r2dii.analysis becuase of an issue that indirectly relates to r2dii.match. This PR avoids failures on CRAN when r2dii.match is unavailable.

Remove CI tests from testthat

---

.github/workflows/render-readme.yaml

This PR aims to compensate for the CI tests that were removed in #360. 
By rendering the `README` file, that runs the entire "PACTA for banks workflow", with dummy data using `r2dii.data` and `r2dii.match`, we test on every PR if the changes to `r2dii.analysis` would be compatible with the upstream packages. 
Closes #361

Update GH actions to render README on push and pr

---

DESCRIPTION
R/utils-pipe.R
R/utils-tidy-eval.R
man/pipe.Rd
man/tidyeval.Rd

Complements #367 
I updated usethis and rerun `use_pipe()` and `use_tidyevel()` hoping the latest version of usethis would add `@return` to those helpfiles. That was the case for pipe but not for tidyeval. 
- Document return value of the pipe via the development version of `usethis::use_pipe()` 
- Run `usethis::use_tidyeval()` plus move things around a bit and add `@return` to meet CRAN's requirement.
I'm still unsure what's the recommended way to deal with this. I searched on rOpenSci's slack and found nothing useful. We may come across some other way but for now this should work.

Add return values for pipe and tidyeval

---

.github/workflows/R-CMD-check.yaml
.github/workflows/R-CMD-check_r2dii-devel.yaml

https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
This need for this change is well documented and this PR touches no production code.
While I'm here I also update the base workflow to reflect latest changes to r-lib/actions.
I'll merge with no further review.﻿

Use latest workflow from r-lib

---

_pkgdown.yml

The News menu has a "Releases" section that I now find confusing
because there are more releases than entries under News/Releases,
pointing to external articles. But we don't write articles for
most small patches.
This PR removes the headings "Releases" and "Changelog", to
instead expose the changelog directly under the News navbar.
The goal is to reduce confusion and to reduce maintenance cost,
by not feeling we need to add an article for small patches. 
An alternative could be to add a single link to the blog, so
users can discover it and then serve themselves what they 
need. 
--
Relates to similar PRs in other r2dii packages (e.g. https://github.com/2DegreesInvesting/r2dii.match/pull/382) but we can discuss only here and then I can apply the decision to all repos.

Simpler News

---

NEWS.md
R/target_sda.R
man/target_sda.Rd
tests/testthat/_snaps/target_sda.md
tests/testthat/test-target_market_share.R
tests/testthat/test-target_sda.R

`target_sda()` gains the argument `region_isos`. This will allow for regional granularity in the `SDA` output. 
One unfortunate note: 
* The function signature of `target_market_share` is: 
`target_market_share(data, ald, scenario, region_isos, use_credit_limit, by_company, weight_production)`
unfortunately, since we are adding `region_isos` to the `target_sda` function AFTER publishing the package, we cannot add the parameter in the same place as `target_market_share()`, it must be added as the final parameter (or else we risk breaking users old code). 
ie. the function of `target_sda()` is: 
`target_sda(data, ald, co2_intensity_scenario, use_credit_limit, by_company, region_isos)`
with `region_isos` being the final argument. 
Would love to hear @AlexAxthelm @cjyetman and @maurolepore …

`target_sda` gains `region_isos` argument

---

NEWS.md
R/summarize_weighted_production.R
R/target_market_share.R
R/target_sda.R
R/utils.R
man/target_sda.Rd
tests/testthat/test-target_market_share.R
tests/testthat/test-target_sda.R

Now:
* `target_sda(..., by_company = FALSE)` will calculate the loan-weighted emission factors, and aggregate them to portfolio level
* `target_sda(..., by_company = TRUE)` will output unweighted emission factors, and output them at company level
Note that the function `target_market_share()` has the argument `weight_production` which allows the user to manually control this behavior. I have elected not to include an analogous `weight_emission_factor` argument in this function, as the weighted but un-aggregated `emission_factor` value is not really interpretable or useful for the user, and would likely just cause confusion. 
Closes #376

`target_sda` now outputs unweighted `emission_factor` by default, if `by_company = TRUE`

---

R/target_sda.R
README.Rmd
README.md
man/target_sda.Rd

Since merging #397, all calls to `target_sda` in `README` and the function documentation lead to 0-row output. 
New argument `region_isos` must be set to `r2dii.data::region_isos_demo` to correctly output data.

Add `region_isos_demo` to `target_sda` calls in README

---

vignettes/r2dii-analysis.Rmd

When adding the new `region_isos`argument to the `target_sda` function, I failed to update the examples in the pkgdown site (in particular `./vignettes/r2dii-analysis.Rmd`) resulting in a null dataframe. 
Relates to #397

Update pkgdown site to use new `region_isos` arg

---

NEWS.md
R/target_sda.R
tests/testthat/test-target_sda.R

This is a bit of a hacky PR that ensure that the output of `target_sda` only contains `sectors` that are mutual to all input datasets (`data`, `ald` and `co2_intensity_scenario`). 
These hacks beg for a larger refactor of the function, but I'd rather get this bug fixed ASAP, and deal with the larger function refactor with less urgency. 
Closes #390

In `target_sda`, remove sectors from `co2_intensity_scenario` if missing from `data` and `ald`

---

tests/testthat/test-summarize_weighted_production.R

These snapshot tests on `demo` data were added when the package was first written, and are very brittle. 
With [this PR](https://github.com/2DegreesInvesting/r2dii.data/pull/280), those tests will now begin to pass warnings. 
Since the output of `summarize_weight_production` is (indirectly) tested extensively in `target_market_share`, I think it is safe to simply remove this brittle test.

Remove brittle snapshot test

---

R/target_market_share.R
R/target_sda.R
R/utils.R
tests/testthat/test-target_market_share.R
tests/testthat/test-target_sda.R

In case the input `region_isos` has upper-cases in `isos`, the `target_market_share` and `target_sda` function will call a function to change the upper-cases to lower-cases and will issue a warning to the user. If this is not done, the joining of `region_isos` outputs 0 rows. 
Closes 398.

Update `target_*` functions to warn and change `isos` to lower-case in `region_isos`

---

NEWS.md
R/target_market_share.R
man/target_market_share.Rd

Expose `green_or_brown` dataset as argument

---

tests/testthat/_snaps/join_abcd_scenario.md
tests/testthat/_snaps/join_ald_scenario.md
tests/testthat/_snaps/target_market_share.md
tests/testthat/_snaps/target_sda.md

Snapshots are very brittle tests, and many things can cause them to change. 
Here, for example, it seems to be a change in `tibble` which changes the way that tables appear/ are printed that caused these snapshots to fail. 
I have updated all of them accordingly. 
Note: I expect checks to still fail, see https://github.com/RMI-PACTA/r2dii.analysis/issues/432 and https://github.com/RMI-PACTA/r2dii.analysis/pull/431

Update test snapshots

---

.github/workflows/pkgdown.yaml

Fixes a bug introduced in #431 
CI did not catch this bug, since all CI was failing at that stage for a different reason.

fix typo in pkgdown yml

---

NEWS.md
R/target_sda.R
tests/testthat/_snaps/target_sda.md
tests/testthat/test-target_sda.R

closes #445 
This PR:
- ensures that `target_sda(by_company = TRUE)` uses the emission intensity value of the final year of the `adjusted_scenario_*` to calculate the `target_*` values for companies when using the SDA approach
- this ensures that - regardless of whether the SDA is applied at company or loan book level - the individual scenario targets converge at the correct scenario value
- the issue had been caused by a `right_join`, that introduces `NAs` for every year past the emission intensity projection when running `target_sda()` at the company level.
- some implementation details:
- previously, `target_summary_groups` was adjusted to loan book or company level at the top level of `target_sda()`
- it is moved into `compute_loanbook_targets()`, which gains an argument, …

fix company level sda targets

---

NEWS.md
R/target_market_share.R
R/utils.R
tests/testthat/test-target_market_share.R

This PR adjusts the expected behaviour of `target_market_share` in how it handles input `abcd` data when `abcd$production` contains `NA`s. Previously it would filter these rows and remove from analysis. Now, it replaces them with `0`. 
@jacobvjk I have a follow-up question, which is, do we want `target_sda` to exhibit the same behaviour? I imagine probably we do. 
and @cjyetman I wanted your input here, do you think this is a reasonable thing to do? (see linked issue for more reference). I know there are, in general, fears around replacing `NA`s with 0s willy nilly, but I think in this particular case, we do actually expect that PAMS data with `NA` production values DO mean 0 production... Especially if the asset has not "turned on" yet.
Closes #423

Fill NAs with zero in `abcd`

---

NEWS.md
R/target_market_share.R
tests/testthat/test-target_market_share.R

`target_market_share` now correctly handles input `scenario` with a hyphen in name

---

R/join_abcd_scenario.R

While working on a separate PR, I noticed some odd behaviour of this internal function. 
The point of `add_green_technologies_to_abcd` is to add green technologies to a matched input dataset if they are not already present. This serves to ensure that green technologies always get a forward-looking target (as is the expectation of SMSP). 
However, this function was erroneously adding the technologies no matter what (even if they were already present in the input). I guess this problem was evened out somewhere else in some call to `summarize`, but I figured it makes sense to just fix it where it happens.
See https://github.com/RMI-PACTA/r2dii.analysis/issues/318 for more info. 
No related issue.

upkeep: `add_green_technologies_to_abcd` only adds techs if they are not already there

---

R/target_market_share.R
inst/WORDLIST
tests/testthat/test-target_market_share.R

closes #489 
- `target_market_share()` gains handling of duplicate `id_loan`s and throws informative error
- `test-target_market_share.R` gains test for this and updates other tests where `id_loan` was implicitly duplicated before

489 check unique id target market share

---

R/join_abcd_scenario.R
tests/testthat/test-target_market_share.R

closes #495 
- `target_market_share()` gains handling that identifies missing low carbon technologies by sector, not overall. This ensures that scenario targets for the companies in the loan book that have missing low carbon technologies will be calculated and returned, even if the company has another sector that does have production values in technologies of the same names as the missing ones.

add correct missing low carbon technologies to abcd

---

.github/workflows/R.yml

- following https://github.com/RMI-PACTA/r2dii.match/pull/504
The compare version action checks for a practice that does not appear to be widely/consistently used in this repo.

disable compare version check

---

R/join_abcd_scenario.R
R/summarize_weighted_production.R
man/join_abcd_scenario.Rd
man/summarize_weighted_production.Rd

relates to #468 
* `join_abcd_scenario()` is soft-deprecated
* `summarize_weighted_production()` and `summarize_weighted_percent_change()` are soft-deprecated
* following the process as described here https://lifecycle.r-lib.org/articles/communicate.html#deprecate-a-function

Soft deprecate funs

---

README.Rmd
README.md

relates to #526 and #468 
* removes explanations of how to use deprecated functions from `README.Rmd` and `README.md`

remove refs to soft-deprecated functiuons in README

---

tests/testthat/test-data_dictionary.R

For some reason, env var `R_CMD` is not set when running `testthat::test_check()` (via `covr::package_coverage()`) on Windows, which leads to an error e.g. https://github.com/RMI-PACTA/r2dii.analysis/actions/runs/13330906300/job/37234562139#step:5:50
This uses `testthat::test_check()`'s internal `TESTTHAT_IS_CHECKING` env var because it also [runs the tests in the context of `R CMD check`](https://testthat.r-lib.org/reference/test_package.html)
https://github.com/r-lib/testthat/blob/50a99ec76fed8140a9211ed862289e877e86614d/R/test-package.R#L49
``` r
test_check <- function(package, reporter = check_reporter(), ...) {
require(package, character.only = TRUE)
options(cli.hyperlink = FALSE)
withr::local_envvar(TESTTHAT_IS_CHECKING = "true")
test_dir(
"testthat",
package = package,
reporter = …
```

skip `data_dictionary` test in `testthat::test_check()` too

---

R/join_abcd_scenario.R
R/target_market_share.R
man/join_abcd_scenario.Rd
tests/testthat/test-join_abcd_scenario.R
tests/testthat/test-summarize_weighted_production.R

* updates tests of deprecated functions following https://lifecycle.r-lib.org/articles/communicate.html#deprecate-a-function (but using expect_warning instead of adding a snapshot test)
* turns the deprecated function `join_abcd_scenario()` into a wrapper around the new internal function `join_abcd_scenario_()` (following the same structure applied for `summarize_weighted_production()`). This allows quelling deprecation warnings in the tests of the exported function while avoiding warnings being thrown when the internal function is called from within `target_market_share()`

Update tests of deprecated functions

---

.github/workflows/testthat.yaml

as in https://github.com/RMI-PACTA/r2dii.plot/pull/596
proof is no skipped tests in the output of the testthat action: https://github.com/RMI-PACTA/r2dii.analysis/actions/runs/13337776560/job/37256580749?pr=537#step:5:147
Just for clarity, there are 2 tests for the data dictionary currently implemented. One tests that all of the columns do not include NA values, which can run during R CMD check and would have caught the problem that I had not filled in the definitions in the RDA file yet. The second one tests that the RDA file is the same as if one ran the build dictionary script during the test, which cannot run during R CMD check and is the one that's most likely to catch future problems where the CSVs are modified but the submitter forgot to run the build dictionary script to update …

add independent {testthat} action so tests that can't run in R CMD check run elsewhere

---

R/target_sda.R
man/target_sda.Rd

#544 introduced a minor bug in the documentation because it was missing a `>`, which caused problems with the HTML rendering of one of the doc pages:
https://rmi-pacta.github.io/r2dii.analysis/dev/reference/target_sda.html

add missing `>` from #544
