RMI-PACTA/r2dii.analysis

man/join_ald_scenario.Rd, tests/testthat/test-join_ald_scenario.R
Relates to 2degreesinvesting/r2dii.data#68
=> Use weo_2019

vignettes/target-market-share.Rmd
Jackson, this rewrite aims to make the tone
of the article more consistent, and more
personal (I write to an imaginary person). 
Along the way I try to understand what you 
wrote by trying to say in my words what I 
think  you intend.
Feel free to rewrite.
=> Reword articles to see if I get it

README.Rmd, README.md
r2dii.analysis is now on CRAN!
I updated the installation instructions on the readme.
=> update readme for cran release

vignettes/r2dii-analysis.Rmd
=> swap `rbind` for `bind_rows` in get started article

_pkgdown.yml, vignettes/production-percent-change.Rmd
=> Add new article to website

.github/workflows/pkgdown.yaml
I expect this PR to fix this problem:
=> Allow tidyverse

NEWS.md, R/target_sda.R, R/utils.R, tests/testthat/test-target_sda.R
Hopefully we squash this bug for real now.
Closes #160
=> target_sda aggregate over plant location

DESCRIPTION, NEWS.md, R/join_ald_scenario.R, R/summarize_weighted_production.R, R/target_market_share.R, R/target_sda.R, R/utils.R, tests/testthat/test-join_ald_scenario.R, tests/testthat/test-target_sda.R
I messed up the setup of the previous PR so I opened a new one.
Relates to 2DegreesInvesting/r2dii.match#257
=> maurolepore join lowercase ald columns

NEWS.md
=> revert increment version in NEWS.md

.github/workflows/R-CMD-check_r2dii-devel.yaml
We can now reproduce problems in reverse dependencies that CRAN detected but not us, for example: https://github.com/2DegreesInvesting/r2dii.analysis/actions/runs/387692571
=> R CMD check with devel version of other r2dii packages

DESCRIPTION, README.md, revdep/README.md
Nothing of this affects code. Just preps for release.
=> Prepare 0.1.3

NEWS.md, README.md, revdep/README.md
Relates to https://github.com/2DegreesInvesting/r2dii.analysis/issues/259
=> Prepare 0.1.4

NEWS.md, R/target_market_share.R, tests/testthat/test-target_market_share.R
This PR is a clean version of #270, which had stray commits. 
Relates to #262
Closes #265
=> Initially aggregate loans by appropriate groups, cleaned

DESCRIPTION, NEWS.md
=> Increment dev version

NEWS.md, R/target_market_share.R, man/target_market_share.Rd, tests/testthat/test-target_market_share.R
=> target_market_share() no longer returns internal columns

NEWS.md, tests/testthat/test-target_market_share.R
=> Test that `target_market_share` fails with differing input currencies

NEWS.md, R/join_ald_scenario.R, README.md
=> Prepare 0.1.10

vignettes/r2dii-analysis.Rmd
=> use r2dii.plot in get started article

vignettes/r2dii-analysis.Rmd
=> use `r2dii.plot::qplot_*` in "Get Started" 

NEWS.md, R/target_sda.R, tests/testthat/test-target_sda.R, vignettes/r2dii-analysis.Rmd
=> `target_sda` filters `scenario` to have consistent start year as `ald`

README.Rmd, README.md, cran-comments.md
Relates to https://github.com/2DegreesInvesting/r2dii.analysis/issues/363
﻿
=> Prepare 0.1.11

cran-comments.md
=> Explain the issue and how we fixed it

DESCRIPTION, man/r2dii.analysis-package.Rd
=> Address CRAN submission notes

DESCRIPTION, NEWS.md, cran-comments.md
=> Submit r2dii.analysis 0.1.12 to CRAN

_pkgdown.yml
This PR touches no production code but changes the website, which faces users. I'd appreciate a review.
=> Update package list on the website to include r2dii.plot

vignettes/target-market-share.Rmd
In the current formulation, the TMSR and SMSP approaches seem very different. By expanding the equation and showing the derivation, I hope to make it more clear to users how similar they actually are. 
@maurolepore not sure if I need to build pkgdown or anything to incorporate these changes? I think this is all done on CI right?
=> Update tmsr explanation in article

R/target_market_share.R, tests/testthat/test-target_market_share.R
This PR is a very focused refactor of `target_market_share()` to tidy up some technical debt that has accumulated, and hopefully make it more clear how the function works. 
The diffs are large, however no tests were touched, and all tests + checks pass as expected, so we can be reasonably sure that the function still works as expected.
=> Refactor `target_market_share()`

DESCRIPTION, man/r2dii.analysis-package.Rd
=> Use roxygen 7.1.2

R/target_sda.R, tests/testthat/test-target_market_share.R, tests/testthat/test-target_sda.R
Relates to PR #388 and @jdhoffa's comments
=> `target_sda` solves issue #224 with a helpful error message

.github/workflows/R-CMD-check.yaml, .github/workflows/R-CMD-check_r2dii-devel.yaml, .github/workflows/pkgdown.yaml, .github/workflows/pr-commands.yaml, .github/workflows/test-coverage.yaml, README.Rmd, README.md, codecov.yml
See https://github.com/2DegreesInvesting/r2dii.data/pull/278 for more context.
Also added necessary dependencies to ensure pkgdown workflow passes.
Closes #387
=> Update to r-lib actions v2

R/join_abcd_scenario.R, R/join_ald_scenario.R, R/summarize_weighted_production.R, R/target_market_share.R, R/target_sda.R, R/utils.R, data-raw/sysdata.R, tests/testthat/_snaps/join_abcd_scenario.md, tests/testthat/_snaps/join_ald_scenario.md, tests/testthat/_snaps/target_market_share.md, tests/testthat/_snaps/target_sda.md
Relates to 2DegreesInvesting/r2dii.analysis#1
Closes #416
=> Fix deprecated usage of `.data` in tidyselect functions

DESCRIPTION, NEWS.md
=> Increment version number to 0.2.1

DESCRIPTION, NEWS.md
=> Increment version number to 0.2.1.9000

DESCRIPTION
=> added Nicky as author to description file

tests/testthat/test-target_sda.R
=> Add test ensuring expected start year of `target_sda`

DESCRIPTION, NEWS.md
=> Increment version number to 0.3.0.9000

.github/workflows/add-prs-and-issues-to-project.yml
See https://github.com/RMI-PACTA/r2dii.data/pull/321
=> Add issues and PRs to maintainer project

.github/workflows/add-prs-and-issues-to-project.yml
See https://github.com/RMI-PACTA/r2dii.match/pull/441
=> Add issues and prs to r2dii suite project

README.Rmd, README.md
This one needed a bit more work!
See https://github.com/RMI-PACTA/r2dii.data/pull/323
=> Update knit and modernize the README

DESCRIPTION
=> Move r2dii.match from Suggests to Imports

DESCRIPTION, R/join_abcd_scenario.R, R/summarize_weighted_production.R, R/target_market_share.R, R/target_sda.R, man/join_abcd_scenario.Rd, man/summarize_weighted_production.Rd, man/target_market_share.Rd, man/target_sda.Rd
Closes #455 
Thanks @maurolepore
=> Use `@examplesIf` and move `r2dii.match` back into `Suggests`

.github/workflows/render-readme.yaml
Relates to https://github.com/RMI-PACTA/r2dii.match/pull/444
Closes #458
=> Fix `render-readme.yaml` action

R/join_abcd_scenario.R, R/summarize_weighted_production.R, R/target_market_share.R, R/target_sda.R, man/join_abcd_scenario.Rd, man/summarize_weighted_production.Rd, man/target_market_share.Rd, man/target_sda.Rd
=> Add missing `"` in exampleIf

DESCRIPTION, _pkgdown.yml
=> feat: point `_pkgdown.yml` to new pkgdown template

NEWS.md, README.md, cran-comments.md
- **polish NEWS.md**
- **build README**
- **update cran-comments.md**
=> release: prepare 0.4.0

DESCRIPTION, NEWS.md
=> Increment version number to 0.4.0

DESCRIPTION, NEWS.md
=> release: Increment version number to 0.4.0.9000

.github/workflows/R.yml
Following https://github.com/RMI-PACTA/actions/pull/96
=> Add revdep checks

_pkgdown.yml
- depends on [pacta.multi.loanbook](https://github.com/rmi-pacta/pacta.multi.loanbook) being released on CRAN
- towards https://github.com/RMI-PACTA/pacta.multi.loanbook/issues/148
=> add pacta.multi.loanbook to pkgs menu

NEWS.md, cran-comments.md, inst/WORDLIST
relates to #525 
* adds `"sda"` to `inst/WORDLIST` to handle spelling note
* updates and polishes `NEWS.md`
* updates `cran-comments.md`
=> Prep release 0.5.0

R/utils.R
should fix the recent {lintr} errors
=> remove explicit returns

NEWS.md, cran-comments.md
relates to #538
- updates and polishes NEWS.md
- updates cran-comments.md
=> Prep release 0.5.1

DESCRIPTION, NEWS.md
relates to #538 
- bump version number to 0.5.1
=> Increment version number to 0.5.1

DESCRIPTION, NEWS.md
closes #538 
- increments version to 0.5.1.9000
=> Increment version number to 0.5.1.9000

DESCRIPTION, NEWS.md
=> Increment version number to 0.5.2.9000

NEWS.md, R/target_sda.R, man/target_sda.Rd
=> update URL to SDA article
